// !!! This is a file automatically generated by hipify!!!
/*
 * ROCm/HIP compatibility shims.
 * Maps CUDA-specific types and APIs to their HIP equivalents so the same
 * source compiles with both nvcc and hipcc (via PyTorch ROCm).
 *
 * This header is included first in every .cu / .cpp source file.
 * On NVIDIA it is a no-op (the real CUDA headers are used).
 */
#pragma once

#ifdef __HIP_PLATFORM_AMD__

/* ---- Core HIP runtime headers ---- */
#include <hip/hip_runtime.h>
#include <hip/hip_fp16.h>
#include <hip/hip_bfloat16.h>

/* ---- CUDA half / bfloat type aliases ---- */
/*  __half   is already defined by hip_fp16.h as the 16-bit float type.
 *  For bfloat16 PyTorch ROCm uses __hip_bfloat16 (from amd_hip_bf16.h).
 *  We expose nv_* aliases used in template specialisations below.       */
using nv_half         = __half;
using nv_bfloat16     = __hip_bfloat16;
using nv_bfloat162    = __hip_bfloat162;
/* __hip_bfloat16 and __hip_bfloat162 may be needed by some template checks */
#ifndef __hip_bfloat16
#define __hip_bfloat16  __hip_bfloat16
#endif
#ifndef __hip_bfloat162
#define __hip_bfloat162 __hip_bfloat162
#endif

/* ---- CUDA → HIP runtime macro aliases ---- */
#define hipStream_t                              hipStream_t
#define hipEvent_t                               hipEvent_t
#define hipEventCreate(e)                        hipEventCreate(e)
#define hipEventRecord(e, s)                     hipEventRecord(e, s)
#define hipEventSynchronize(e)                   hipEventSynchronize(e)
#define hipEventDestroy(e)                       hipEventDestroy(e)
#define hipStreamCreate(s)                       hipStreamCreate(s)
#define hipStreamDestroy(s)                      hipStreamDestroy(s)
#define hipStreamSynchronize(s)                  hipStreamSynchronize(s)
#define hipStreamWaitEvent(s, e, f)              hipStreamWaitEvent(s, e, f)
#define hipGetDevice(d)                          hipGetDevice(d)
#define hipSetDevice(d)                          hipSetDevice(d)
#define hipDeviceGetAttribute(v, a, d)           hipDeviceGetAttribute(v, a, d)
#define hipDeviceAttributeMultiprocessorCount            hipDeviceAttributeMultiprocessorCount
#define hipMalloc(p, s)                          hipMalloc(p, s)
#define hipFree(p)                               hipFree(p)
#define hipHostMalloc(p, s)                      hipHostMalloc(p, s, 0)
#define hipHostFree(p)                           hipHostFree(p)
#define hipMemcpy(d, s, n, k)                    hipMemcpy(d, s, n, k)
#define hipMemcpyAsync(d, s, n, k, st)           hipMemcpyAsync(d, s, n, k, st)
#define hipMemcpyHostToDevice                    hipMemcpyHostToDevice
#define hipMemcpyDeviceToHost                    hipMemcpyDeviceToHost
#define hipMemcpyDeviceToDevice                  hipMemcpyDeviceToDevice
#define hipMemset(p, v, n)                       hipMemset(p, v, n)
#define hipSuccess                               hipSuccess
#define hipErrorInvalidValue                     hipErrorInvalidValue
#define hipLaunchKernel                          hipLaunchKernel
#define hipOccupancyMaxActiveBlocksPerMultiprocessor \
        hipOccupancyMaxActiveBlocksPerMultiprocessor

/* ---- __ldg: HIP supports __ldg natively for scalar types ---- */
#ifndef __ldg
#define __ldg(ptr) (*(ptr))
#endif

/* ---- __umulhi: HIP already provides this in amd_device_functions.h ---- */
/* Do NOT redefine; it's available after including hip_runtime.h          */

/* ---- Warp-level: __shfl_sync → __shfl ---- */
/* HIP wavefronts are 64-wide by default on MI300/MI355 but warp-level     */
/* ops use 32-wide SIMD groups when launched with 32-thread warps.          */
/* The mask argument is ignored on HIP (all active lanes participate).      */
#define __shfl_sync(mask, val, src_lane)       __shfl(val, src_lane)
/* Note: the 4-arg form with width is rare; add if needed:                 */
/* #define __shfl_sync(mask,val,src,width)  __shfl(val,src,width)          */

/* ---- FP8 support: conditional on architecture ---- */
#if defined(__gfx950__) || defined(__gfx942__) || defined(__gfx941__) || defined(__gfx940__)
#define HW_FP8_CONVERSION_ENABLED
#include <hip/hip_fp8.h>
#endif

/* ---- cudaCheck helper ---- */
#include <cstdio>
#include <cstdlib>
#ifndef hipCheck
#define hipCheck(call)                                                         \
    do {                                                                       \
        hipError_t _e = (call);                                                \
        if (_e != hipSuccess) {                                                \
            fprintf(stderr, "HIP error %s at %s:%d\n",                        \
                    hipGetErrorString(_e), __FILE__, __LINE__);                \
            abort();                                                           \
        }                                                                      \
    } while (0)
#endif
#define cudaCheck(call) hipCheck(call)

#else  /* ---- NVIDIA CUDA path: minimal shims ---- */

#include <hip/hip_runtime.h>
#include <hip/hip_fp16.h>
#include <hip/hip_bf16.h>
using nv_half     = __half;
using nv_bfloat16 = __hip_bfloat16;
using nv_bfloat162= __hip_bfloat162;

#ifndef cudaCheck
#include <cstdio>
#include <cstdlib>
#define cudaCheck(call)                                                        \
    do {                                                                       \
        hipError_t _e = (call);                                               \
        if (_e != hipSuccess) {                                               \
            fprintf(stderr, "CUDA error %s at %s:%d\n",                       \
                    hipGetErrorString(_e), __FILE__, __LINE__);               \
            abort();                                                           \
        }                                                                      \
    } while (0)
#endif

#endif /* __HIP_PLATFORM_AMD__ */
